### ISSUE TITLE
有没有考虑做成一个服务

### ISSUE THREAD

**Issue by Desgard** [baijiangliang/year2018#7]
从头条圈看到的，同时也是 GitHub 客户端 Sepicat 的作者 😁
感觉这个脚本完全可以做成服务化，通过 HTML 支持用户输入和分析数据图浏览器输出，感觉会有更好的传播（或许可以共建一下）。

**Comment by baijiangliang** [comment]
脚本必须在本地跑，不可能让用户把非公开的仓库上传到服务端。数据展示可以 web 化。你想做成服务的话欢迎啊，但是有多少人会用就不知道了...
